<?php
declare(strict_types=1);

namespace Plaisio;

/**
 * Class for holding all constants generated by PhpStratum.
 */
class C
{
  const OPEN_DATE_STOP = '9999-12-31';
  const LAN_ID_BABEL_REFERENCE = 2;

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * @setbased.stratum.constants
   *
   * Below this doc block constants will be inserted by PhpStratum.
   */

  //--------------------------------------------------------------------------------------------------------------------
}

//----------------------------------------------------------------------------------------------------------------------
