/**
 * Deletes cached menu HTML code for a profile
 *
 * @param p_cmp_id The ID of the company (safe guard).
 * @param p_pro_id The ID of the profile.
 */
create procedure abc_menu_core_cache_flush_by_pro_id(in p_cmp_id @abc_menu_cache.cmp_id%type@,
                                                     in p_pro_id @abc_menu_cache.pro_id%type@)
modifies sql data
-- type: none
begin
  delete from ABC_MENU_CACHE
  where  cmp_id = p_cmp_id
  and    pro_id = p_pro_id
  ;
end
