/**
 * Deletes cached menu HTML code for a profile
 *
 * @param p_cmp_id The ID of the company (safeguard).
 * @param p_pro_id The ID of the profile.
 *
 * @type none
 */
create procedure abc_menu_core_cache_flush_by_pro_id
(
  in p_cmp_id smallint(5) unsigned, -- type: ABC_MENU_CACHE.cmp_id
  in p_pro_id smallint(5) unsigned --  type: ABC_MENU_CACHE.pro_id
)
  modifies sql data
begin
  delete
  from ABC_MENU_CACHE
  where cmp_id = p_cmp_id
    and pro_id = p_pro_id;
end
